stages:
    - build

build:
    stage: build
    before_script:
        - npm install
    cache:
        untracked: true
    only:
        - master
    script:
        - echo "Dependencies installed"
        - docker run --detached hello-world
