stages:
    - build

build:
    stage: build
    image: node:6.11.2
    before_script:
        - npm install
    cache:
        untracked: true
    only:
        - master
    script:
        - npm -v
